#!/bin/sh

GIT_INFO="$(git config --list)"

USERNAME=$(echo "$GIT_INFO" | grep 'user.name' | cut -d '=' -f 2)

BRANCH="$(git rev-parse --abbrev-ref HEAD)"

echo Running build
echo ===============================
if ! npm run build; then
    echo Error building. Rejecting commit.
    curl -X 'POST' \
      'https://email-service-afdc.onrender.com/email' \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d '{
      "body": "El usuario '$USERNAME' ha utilizado el hook build-hook el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' en la rama '$BRANCH'. El resultado es: rechazado."
    }'
    exit 1
fi

curl -X 'POST' \
  'https://email-service-afdc.onrender.com/email' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "body": "El usuario '$USERNAME' ha utilizado el hook build-hook el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' en la rama '$BRANCH'. En resultado es: aceptado"
}'
exit 0