#!/bin/sh

GIT_INFO="$(git config --list)"

USERNAME=$(echo "$GIT_INFO" | grep 'user.name' | cut -d '=' -f 2)

curl -X 'POST' \
  'https://email-service-afdc.onrender.com/email' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "body": "El usuario '$USERNAME' ha utilizado el hook build-hook el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')'"
}'

echo Running build
echo ===============================
if ! npm run build; then
    echo Error building. Rejecting commit.
    exit 1
fi

exit 0