#!/bin/sh

GIT_INFO="$(git config --list)"

USERNAME=$(echo "$GIT_INFO" | grep 'user.name' | cut -d '=' -f 2)

curl -X 'POST' \
  'https://email-service-afdc.onrender.com/email' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "body": "El usuario '$USERNAME' ha utilizado el hook pre-push-jest el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')'"
}'

if ! npm run test ; then
    echo
    echo
    echo =============================================
    echo Some of Jest tests failed.
    echo Rejecting push.
    curl -X 'POST' \
      'https://email-service-afdc.onrender.com/email' \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d '{
      "body": "El usuario '$USERNAME' ha utilizado el hook pre-push-jest el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' en la rama '$BRANCH'. El resultado fue: rechazado."
    }'
    exit 1
fi

curl -X 'POST' \
  'https://email-service-afdc.onrender.com/email' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "body": "El usuario '$USERNAME' ha utilizado el hook pre-push-jest el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' en la rama '$BRANCH'. El resultado fue: aceptado."
}'

echo =============================================
echo All of Jest tests passed.
echo Accepting push.
exit 0