#!/bin/sh

GIT_INFO="$(git config --list)"

USERNAME=$(echo "$GIT_INFO" | grep 'user.name' | cut -d '=' -f 2)

BRANCH="$(git rev-parse --abbrev-ref HEAD)"

curl -X 'POST' \
  'https://email-service-afdc.onrender.com/email' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "body": "El usuario '$USERNAME' ha utilizado el hook pre-commit el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' a la rama '$BRANCH'"
}'

if ! npm run test ; then
    echo
    echo
    echo =============================================
    echo Some of Jest tests failed.
    echo Rejecting push.
    exit 1
fi

echo =============================================
echo All of Jest tests passed.
echo Accepting push.
exit 0