#!/bin/sh

if ! npm run test ; then
    echo
    echo
    echo =============================================
    echo Some of Jest tests failed.
    echo Rejecting push.
    exit 1
fi

echo =============================================
echo All of Jest tests passed.
echo Accepting push.
exit 0