#!/bin/sh

GIT_INFO="$(git config --list)"

USERNAME=$(echo "$GIT_INFO" | grep 'user.name' | cut -d '=' -f 2)

curl -X 'POST' \
  'https://email-service-afdc.onrender.com/email' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "body": "El usuario '$USERNAME' ha utilizado el hook pre-commit el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')'"
}'

BRANCH="$(git rev-parse --abbrev-ref HEAD)"

if [ "$BRANCH" = "main" ]; then
  echo "You can't commit directly to '"${BRANCH}"' branch"
  curl -X 'POST' \
    'https://email-service-afdc.onrender.com/email' \
    -H 'accept: application/json' \
    -H 'Content-Type: application/json' \
    -d '{
    "body": "El usuario '$USERNAME' ha utilizado el hook pre-commit el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' en la rama '$BRANCH'. El resultado es: rechzado."
  }'
  exit 1
fi

echo Running ESLint
echo ===============================
if ! npm run lint; then
    echo ESLint has warning or errors. Fix them before commiting.
    curl -X 'POST' \
      'https://email-service-afdc.onrender.com/email' \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d '{
      "body": "El usuario '$USERNAME' ha utilizado el hook pre-commit el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' en la rama '$BRANCH'.  El resultado es: rechazado."
    }'
    exit 1
fi

echo All good. Allowing commit to proceed.
curl -X 'POST' \
  'https://email-service-afdc.onrender.com/email' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "body": "El usuario '$USERNAME' ha utilizado el hook pre-commit el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' en la rama '$BRANCH'. El resultado es: aceptado."
}'
exit 0