#!/bin/sh

GIT_INFO="$(git config --list)"

USERNAME=$(echo "$GIT_INFO" | grep 'user.name' | cut -d '=' -f 2)

BRANCH="$(git rev-parse --abbrev-ref HEAD)"

if [ "$BRANCH" = "main" ]; then
  echo "You can't commit directly to '"${BRANCH}"' branch"
  curl -X 'POST' \
    'https://email-service-afdc.onrender.com/email' \
    -H 'accept: application/json' \
    -H 'Content-Type: application/json' \
    -d '{
    "body": "El usuario '$USERNAME' ha utilizado el hook pre-push el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' en la rama '$BRANCH'. El resultado es: rechazado."
  }'
  exit 1
fi

echo Running ESLint
echo ===============================
if ! npm run lint; then
    echo ESLint has warning or errors. Fix them before pushing.
    curl -X 'POST' \
      'https://email-service-afdc.onrender.com/email' \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d '{
      "body": "El usuario '$USERNAME' ha utilizado el hook pre-push el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' en la rama '$BRANCH'. El resultado es: rechazado."
    }'
    exit 1
fi

echo All good. Allowing commit to proceed.

if ! npm run test ; then
    echo
    echo
    echo =============================================
    echo Some of Jest tests failed.
    echo Rejecting push.
    curl -X 'POST' \
      'https://email-service-afdc.onrender.com/email' \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d '{
      "body": "El usuario '$USERNAME' ha utilizado el hook pre-push el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' en la rama '$BRANCH'. El resultado es: rechazado."
    }'
    exit 1
fi

echo =============================================
echo All of Jest tests passed.

echo Running build
echo ===============================
if ! npm run build; then
    echo Error building. Rejecting push.
    curl -X 'POST' \
      'https://email-service-afdc.onrender.com/email' \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d '{
      "body": "El usuario '$USERNAME' ha utilizado el hook pre-push el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' en la rama '$BRANCH'. El resultado es: rechazado."
    }'
    exit 1
fi

echo Accepting push.
curl -X 'POST' \
  'https://email-service-afdc.onrender.com/email' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "body": "El usuario '$USERNAME' ha utilizado el hook pre-push el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' en la rama '$BRANCH'. El resultado es: aceptado."
}'
exit 0